/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as SendRouteImport } from './routes/send'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as LabIdRouteImport } from './routes/lab.$id'
import { Route as SessionCodeRouteImport } from './routes/session.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const LabIdRoute = LabIdRouteImport.update({
  id: '/lab/$id',
  path: '/lab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionCodeRoute = SessionCodeRouteImport.update({
  id: '/session/$code',
  path: '/session/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/join/$code': typeof JoinCodeRoute
  '/lab/$id': typeof LabIdRoute
  '/session/$code': typeof SessionCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/join/$code': typeof JoinCodeRoute
  '/lab/$id': typeof LabIdRoute
  '/session/$code': typeof SessionCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/join/$code': typeof JoinCodeRoute
  '/lab/$id': typeof LabIdRoute
  '/session/$code': typeof SessionCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/scan' | '/send' | '/join/$code' | '/lab/$id' | '/session/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scan' | '/send' | '/join/$code' | '/lab/$id' | '/session/$code'
  id:
    | '__root__'
    | '/'
    | '/scan'
    | '/send'
    | '/join/$code'
    | '/lab/$id'
    | '/session/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScanRoute: typeof ScanRoute
  SendRoute: typeof SendRoute
  JoinCodeRoute: typeof JoinCodeRoute
  LabIdRoute: typeof LabIdRoute
  SessionCodeRoute: typeof SessionCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/$id': {
      id: '/lab/$id'
      path: '/lab/$id'
      fullPath: '/lab/$id'
      preLoaderRoute: typeof LabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$code': {
      id: '/session/$code'
      path: '/session/$code'
      fullPath: '/session/$code'
      preLoaderRoute: typeof SessionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScanRoute: ScanRoute,
  SendRoute: SendRoute,
  JoinCodeRoute: JoinCodeRoute,
  LabIdRoute: LabIdRoute,
  SessionCodeRoute: SessionCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
